### ISSUE TITLE
Argument 1 passed to elgg_push_entity_breadcrumbs() must be an instance of ElggEntity, null given

### ISSUE THREAD

**Issue by rohit1290** [ColdTrick/event_manager#146]
```
ELGG.CRITICAL: Exception at time 1557088828:
TypeError: Argument 1 passed to elgg_push_entity_breadcrumbs() must be an instance of ElggEntity, null given, called in /home/username/public_html/mod/event_manager/views/default/resources/event/unsubscribe/request.php on line 15 and defined in /home/username/public_html/vendor/elgg/elgg/engine/lib/navigation.php:431
Stack trace:
#0 /home/username/public_html/mod/event_manager/views/default/resources/event/unsubscribe/request.php(15): elgg_push_entity_breadcrumbs(NULL)
#1 /home/username/public_html/vendor/elgg/elgg/engine/classes/Elgg/ViewsService.php(522): include('/home/username/pu...')
#2 /home/username/public_html/vendor/elgg/elgg/engine/classes/Elgg/ViewsService.php(455): Elgg\ViewsService->renderViewFile('resources/event...', Array, 'default', true)
#3 /home/username/public_html/vendor/elgg/elgg/engine/lib/views.php(428): Elgg\ViewsService->renderView('resources/event...', Array)
#4 /home/username/public_html/vendor/elgg/elgg/engine/classes/Elgg/Router.php(260): elgg_view_resource('event/unsubscri...', Array)
#5 /home/username/public_html/vendor/elgg/elgg/engine/classes/Elgg/Router.php(124): Elgg\Router->prepareResponse(Object(Elgg\Http\Request))
#6 /home/username/public_html/vendor/elgg/elgg/engine/classes/Elgg/Router.php(98): Elgg\Router->getResponse(Object(Elgg\Http\Request))
#7 /home/username/public_html/vendor/elgg/elgg/engine/classes/Elgg/Application.php(467): Elgg\Router->route(Object(Elgg\Http\Request))
#8 /home/username/public_html/vendor/elgg/elgg/engine/classes/Elgg/Application.php(362): Elgg\Application->run()
#9 /home/username/public_html/vendor/elgg/elgg/engine/classes/Elgg/Application.php(418): Elgg\Application::route(Object(Elgg\Http\Request))
#10 /home/username/public_html/index.php(8): Elgg\Application::index()
```

I saw this error in my error_log thrice for today.

**Comment by rohit1290** [comment]
@jdalsem @jeabakker 
I have created a PR to fix the issue but it has not yet merged in the repo. Is there any issue with the PR?

**Comment by jdalsem** [comment]
Nope, i just missed it :)
